defmodule Backend.Repo.Migrations.Update do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Passo 1: Remover a constraint da chave primária antiga ANTES de criar user_identities
    execute("ALTER TABLE users DROP CONSTRAINT users_pkey")

    # Passo 2: Criar a nova chave primária baseada apenas no campo id
    execute("ALTER TABLE users ADD PRIMARY KEY (id)")

    # Passo 3: Criar a tabela user_identities depois que users foi ajustado
    create table(:user_identities, primary_key: false) do
      add :refresh_token, :text
      add :access_token_expires_at, :utc_datetime_usec
      add :access_token, :text
      add :uid, :text, null: false
      add :strategy, :text, null: false
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
        references(:users,
          column: :id,
          name: "user_identities_user_id_fkey",
          type: :uuid,
          prefix: "public"
        )
    end

    # Passo 4: Modificar a coluna email
    alter table(:users) do
      modify :email, :citext
    end

    # Passo 5: Criar índices únicos
    create unique_index(:users, [:email], name: "users_unique_email_index")

    create unique_index(:user_identities, [:strategy, :uid, :user_id],
      name: "user_identities_unique_on_strategy_and_uid_and_user_id_index"
    )

  end

  def down do
    drop_if_exists unique_index(:user_identities, [:strategy, :uid, :user_id],
                     name: "user_identities_unique_on_strategy_and_uid_and_user_id_index"
                   )

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:users) do
      modify :email, :text
    end

    execute("ALTER TABLE \"users\" DROP constraint users_pkey")

    execute("ALTER TABLE \"users\" ADD PRIMARY KEY (email, id)")

    drop constraint(:user_identities, "user_identities_user_id_fkey")

    drop table(:user_identities)
  end
end
