defmodule Backend.Repo.Migrations.Fixes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:responses, "responses_author_id_fkey")

    alter table(:responses) do
      modify :author_id,
             references(:users,
               column: :id,
               name: "responses_author_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:responses, "responses_author_id_fkey")

    alter table(:responses) do
      modify :author_id,
             references(:users,
               column: :id,
               name: "responses_author_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
