defmodule Backend.Repo.Migrations.BillingAdded do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :url, :text, null: false
    end

    create table(:billings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version, :bigint, null: false, default: 1
      add :price, :text, null: false
      add :method, :text, null: false
      add :city, :text, null: false
      add :name, :text, null: false
      add :qr_code, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :classroom_id,
          references(:classrooms,
            column: :id,
            name: "billings_classroom_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(:billings, "billings_classroom_id_fkey")

    drop table(:billings)

    alter table(:events) do
      remove :url
    end
  end
end
