defmodule Backend.Repo.Migrations.AddingLockToClassResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:students) do
      add :version, :bigint, null: false, default: 1
    end

    alter table(:events) do
      add :version, :bigint, null: false, default: 1
    end

    alter table(:enrollments) do
      add :version, :bigint, null: false, default: 1
    end
  end

  def down do
    alter table(:enrollments) do
      remove :version
    end

    alter table(:events) do
      remove :version
    end

    alter table(:students) do
      remove :version
    end
  end
end
