defmodule Backend.Repo.Migrations.UpdateBilling do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:billings) do
      remove :key
      remove :price
      add :transaction_amount, :float
      add :pix_key, :text, null: false
      add :city, :text, null: false
    end
  end

  def down do
    alter table(:billings) do
      remove :city
      remove :pix_key
      remove :transaction_amount
      add :price, :text, null: false
      add :key, :text, null: false
    end
  end
end
