defmodule Backend.Repo.Migrations.ChangingEmail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :email, :text
    end

    create unique_index(:users, [:id], name: "users_id_identity_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:id], name: "users_id_identity_index")

    alter table(:users) do
      modify :email, :citext
    end
  end
end
