defmodule Backend.Repo.Migrations.Changes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:user_identities, [:uid, :strategy],
             name: "user_identities_unique_identity_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_identities, [:uid, :strategy],
                     name: "user_identities_unique_identity_index"
                   )
  end
end
