defmodule Backend.Repo.Migrations.UpdateClassroom do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:classrooms) do
      add :is_external, :boolean, default: true
    end
  end

  def down do
    alter table(:classrooms) do
      remove :is_external
    end
  end
end
