defmodule Backend.Repo.Migrations.CreatePostsUpdateTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :email, :citext
    end

    alter table(:students) do
      modify :email, :citext
    end

    create table(:responses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :author_id,
          references(:users,
            column: :id,
            name: "responses_author_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :post_id,
          references(:posts,
            column: :id,
            name: "responses_post_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    alter table(:events) do
      modify :event_date, :utc_datetime
    end
  end

  def down do
    alter table(:events) do
      modify :event_date, :date
    end

    drop constraint(:responses, "responses_author_id_fkey")

    drop constraint(:responses, "responses_post_id_fkey")

    drop table(:responses)

    alter table(:students) do
      modify :email, :text
    end

    alter table(:users) do
      modify :email, :text
    end
  end
end
