defmodule Backend.Repo.Migrations.Billing do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:billings) do
      remove :city
      remove :method
      add :key, :text, null: false
    end
  end

  def down do
    alter table(:billings) do
      remove :key
      add :method, :text, null: false
      add :city, :text, null: false
    end
  end
end
