defmodule Backend.Repo.Migrations.IdentityParaEnrollment do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:enrollments, [:student_id, :classroom_id],
             name: "enrollments_unique_student_classroom_index"
           )
  end

  def down do
    drop_if_exists unique_index(:enrollments, [:student_id, :classroom_id],
                     name: "enrollments_unique_student_classroom_index"
                   )
  end
end
