defmodule Backend.Repo.Migrations.DeletionOnCascade do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:students, "students_user_id_fkey")

    alter table(:students) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "students_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:posts, "posts_author_id_fkey")

    drop constraint(:posts, "posts_classroom_id_fkey")

    alter table(:posts) do
      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "posts_classroom_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :author_id,
             references(:users,
               column: :id,
               name: "posts_author_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:events, "events_classroom_id_fkey")

    alter table(:events) do
      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "events_classroom_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:enrollments, "enrollments_classroom_id_fkey")

    drop constraint(:enrollments, "enrollments_student_id_fkey")

    alter table(:enrollments) do
      modify :student_id,
             references(:students,
               column: :id,
               name: "enrollments_student_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "enrollments_classroom_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:classroom_owners, "classroom_owners_user_id_fkey")

    drop constraint(:classroom_owners, "classroom_owners_classroom_id_fkey")

    alter table(:classroom_owners) do
      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "classroom_owners_classroom_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "classroom_owners_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

  end

  def down do
    drop constraint(:classroom_owners, "classroom_owners_classroom_id_fkey")

    drop constraint(:classroom_owners, "classroom_owners_user_id_fkey")

    alter table(:classroom_owners) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "classroom_owners_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "classroom_owners_classroom_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:enrollments, "enrollments_student_id_fkey")

    drop constraint(:enrollments, "enrollments_classroom_id_fkey")

    alter table(:enrollments) do
      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "enrollments_classroom_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :student_id,
             references(:students,
               column: :id,
               name: "enrollments_student_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:events, "events_classroom_id_fkey")

    alter table(:events) do
      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "events_classroom_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:posts, "posts_classroom_id_fkey")

    drop constraint(:posts, "posts_author_id_fkey")

    alter table(:posts) do
      modify :author_id,
             references(:users,
               column: :id,
               name: "posts_author_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "posts_classroom_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:students, "students_user_id_fkey")

    alter table(:students) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "students_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
