defmodule Backend.Repo.Migrations.ChangingEventsToIncludeReocurrence do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      remove :recurrence_interval
      add :recurrence_days_of_week, {:array, :text}
      add :recurrence_ends_at, :date
    end
  end

  def down do
    alter table(:events) do
      remove :recurrence_ends_at
      remove :recurrence_days_of_week
      add :recurrence_interval, :text
    end
  end
end
