defmodule Backend.Repo.Migrations.CreateInitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :name, :text, null: false
      add :picture, :text
    end

    create unique_index(:users, [:id], name: "users_id_identity_index")

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:user_identities, primary_key: false) do
      add :refresh_token, :text
      add :access_token_expires_at, :utc_datetime_usec
      add :access_token, :text
      add :uid, :text, null: false
      add :strategy, :text, null: false
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "user_identities_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:user_identities, [:uid, :strategy],
             name: "user_identities_unique_identity_index"
           )

    create unique_index(:user_identities, [:strategy, :uid, :user_id],
             name: "user_identities_unique_on_strategy_and_uid_and_user_id_index"
           )

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:students, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version, :bigint, null: false, default: 1
      add :email, :citext, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "students_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create unique_index(:students, [:email], name: "students_unique_email_index")

    create table(:responses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :author_id,
          references(:users,
            column: :id,
            name: "responses_author_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :post_id, :uuid
    end

    create table(:posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:responses) do
      modify :post_id,
             references(:posts,
               column: :id,
               name: "responses_post_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:posts) do
      add :version, :bigint, null: false, default: 1
      add :content, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :classroom_id, :uuid
      add :author_id, :uuid
    end

    create table(:events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version, :bigint, null: false, default: 1
      add :event_date, :utc_datetime, null: false
      add :start_time, :time, null: false
      add :end_time, :time, null: false
      add :url, :text, null: false
      add :event_type, :text, null: false
      add :description, :text
      add :is_recurring, :boolean, default: false
      add :recurrence_interval, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :classroom_id, :uuid
    end

    create table(:enrollments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version, :bigint, null: false, default: 1
      add :status, :text, null: false
      add :is_delinquent, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :student_id,
          references(:students,
            column: :id,
            name: "enrollments_student_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :classroom_id, :uuid
    end

    create table(:classrooms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:posts) do
      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "posts_classroom_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :author_id,
             references(:users,
               column: :id,
               name: "posts_author_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:events) do
      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "events_classroom_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:enrollments) do
      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "enrollments_classroom_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:classrooms) do
      add :version, :bigint, null: false, default: 1
      add :name, :text, null: false
      add :is_external, :boolean, default: true
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:classroom_owners, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :classroom_id,
          references(:classrooms,
            column: :id,
            name: "classroom_owners_classroom_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :user_id,
          references(:users,
            column: :id,
            name: "classroom_owners_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create table(:billings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version, :bigint, null: false, default: 1
      add :price, :text, null: false
      add :method, :text, null: false
      add :city, :text, null: false
      add :name, :text, null: false
      add :qr_code, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :classroom_id,
          references(:classrooms,
            column: :id,
            name: "billings_classroom_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(:billings, "billings_classroom_id_fkey")

    drop table(:billings)

    drop constraint(:classroom_owners, "classroom_owners_classroom_id_fkey")

    drop constraint(:classroom_owners, "classroom_owners_user_id_fkey")

    drop table(:classroom_owners)

    alter table(:classrooms) do
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :is_external
      remove :name
      remove :version
    end

    drop constraint(:enrollments, "enrollments_classroom_id_fkey")

    alter table(:enrollments) do
      modify :classroom_id, :uuid
    end

    drop constraint(:events, "events_classroom_id_fkey")

    alter table(:events) do
      modify :classroom_id, :uuid
    end

    drop constraint(:posts, "posts_classroom_id_fkey")

    drop constraint(:posts, "posts_author_id_fkey")

    alter table(:posts) do
      modify :author_id, :uuid
      modify :classroom_id, :uuid
    end

    drop table(:classrooms)

    drop constraint(:enrollments, "enrollments_student_id_fkey")

    drop table(:enrollments)

    drop table(:events)

    alter table(:posts) do
      remove :author_id
      remove :classroom_id
      remove :updated_at
      remove :inserted_at
      remove :content
      remove :version
    end

    drop constraint(:responses, "responses_post_id_fkey")

    alter table(:responses) do
      modify :post_id, :uuid
    end

    drop table(:posts)

    drop constraint(:responses, "responses_author_id_fkey")

    drop table(:responses)

    drop_if_exists unique_index(:students, [:email], name: "students_unique_email_index")

    drop constraint(:students, "students_user_id_fkey")

    drop table(:students)

    drop table(:tokens)

    drop_if_exists unique_index(:user_identities, [:strategy, :uid, :user_id],
                     name: "user_identities_unique_on_strategy_and_uid_and_user_id_index"
                   )

    drop_if_exists unique_index(:user_identities, [:uid, :strategy],
                     name: "user_identities_unique_identity_index"
                   )

    drop constraint(:user_identities, "user_identities_user_id_fkey")

    drop table(:user_identities)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop_if_exists unique_index(:users, [:id], name: "users_id_identity_index")

    drop table(:users)
  end
end
