defmodule Backend.Repo.Migrations.AddUsersInfo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :name, :text, null: false
      add :hashed_password, :text
    end
  end

  def down do
    alter table(:users) do
      remove :hashed_password
      remove :name
    end
  end
end
