defmodule Backend.Repo.Migrations.Change do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :picture, :text
    end
  end

  def down do
    alter table(:users) do
      remove :picture
    end
  end
end
