defmodule Backend.Repo.Migrations.AddTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:students, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "students_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :classroom_id,
          references(:classrooms,
            column: :id,
            name: "posts_classroom_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :author_id,
          references(:users,
            column: :id,
            name: "posts_author_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_date, :date, null: false
      add :start_time, :time, null: false
      add :end_time, :time, null: false
      add :event_type, :text, null: false
      add :description, :text
      add :is_recurring, :boolean, default: false
      add :recurrence_interval, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :classroom_id,
          references(:classrooms,
            column: :id,
            name: "events_classroom_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:enrollments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false
      add :is_delinquent, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :student_id,
          references(:students,
            column: :id,
            name: "enrollments_student_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :classroom_id,
          references(:classrooms,
            column: :id,
            name: "enrollments_classroom_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:classroom_owners, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :classroom_id,
          references(:classrooms,
            column: :id,
            name: "classroom_owners_classroom_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :user_id,
          references(:users,
            column: :id,
            name: "classroom_owners_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:classroom_owners, "classroom_owners_classroom_id_fkey")

    drop constraint(:classroom_owners, "classroom_owners_user_id_fkey")

    drop table(:classroom_owners)

    drop constraint(:enrollments, "enrollments_student_id_fkey")

    drop constraint(:enrollments, "enrollments_classroom_id_fkey")

    drop table(:enrollments)

    drop constraint(:events, "events_classroom_id_fkey")

    drop table(:events)

    drop constraint(:posts, "posts_classroom_id_fkey")

    drop constraint(:posts, "posts_author_id_fkey")

    drop table(:posts)

    drop constraint(:students, "students_user_id_fkey")

    drop table(:students)
  end
end
