defmodule Backend.Repo.Migrations.AddUsersEmail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("users", "users_pkey")

    alter table(:users) do
      add :email, :text, null: false
    end

    execute("ALTER TABLE \"users\" ADD PRIMARY KEY (email, id)")
  end

  def down do
    drop constraint("users", "users_pkey")

    alter table(:users) do
      remove :email
    end

    execute("ALTER TABLE \"users\" ADD PRIMARY KEY (id)")
  end
end
